# Generated by Django 2.0.13 on 2019-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='create data')),
                ('update_date', models.DateTimeField(verbose_name='Update data')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.IntegerField(default=0)),
                ('frequency', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(verbose_name='create data')),
                ('update_date', models.DateTimeField(verbose_name='Update data')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='create date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Family')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
