# Generated by Django 2.0.13 on 2019-12-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='creation_date',
            field=models.DateTimeField(verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='family',
            name='update_date',
            field=models.DateTimeField(verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateTimeField(verbose_name='Update date'),
        ),
    ]
